### ISSUE TITLE
Database Table : Impounds  missing .

### ISSUE THREAD

**Issue by LaNataliaaa** [REFUZiON312/os-rpSAMP#1]
I'm trying to run the server, but I keep getting the Impounds table missing. I'd appreciate if you could add it to the sql file. Thanks ^^ . Great Gamemode and great work so far. My Congratulations. Thanks a lot for sharing.

**Comment by markostreet** [comment]
Added and Fixed!

**Comment by REFUZiON312** [comment]
Yes I have added it to the sql. Download the osrp.sql file and import it into your database, it should be fully working now. Thanks for reporting your issue.
